/**
 * 라벨 상수 정의
 */
export const LABELS = {
  MANUAL_INPUT: '직접 입력하기',
  EXCEL_UPLOAD: '엑셀 파일로 일괄 등록',
  DOWNLOAD_ALL_XLSX: '전체목록 XLSX 다운로드',
} as const;

export const TABLE_LABELS = {
  RECOMMENDED_QUESTION: {
    QST_ID: 'qstId',
    SERVICE_CD: 'serviceCd',
    SERVICE_NM: 'serviceNm',
    DISPLAY_CTNT: 'displayCtnt',
    PROMPT_CTNT: 'promptCtnt',
    QST_CTGR: 'qstCtgr',
    QST_STYLE: 'qstStyle',
    PARENT_ID: 'parentId',
    PARENT_NM: 'parentNm',
    AGE_GRP: 'ageGrp',
    SHOW_U17: 'showU17',
    IMP_START_DATE: 'impStartDate',
    IMP_END_DATE: 'impEndDate',
    STATUS: 'status',
    CREATED_AT: 'createdAt',
    UPDATED_AT: 'updatedAt',
    LOCKED: 'locked',
  },
  APP_SCHEME: {
    NO: 'no',
    APP_SCHEME_ID: 'appSchemeId',
    PRODUCT_MENU_NAME: 'productMenuName',
    DESCRIPTION: 'description',
    APP_SCHEME_LINK: 'appSchemeLink',
    ONE_LINK: 'oneLink',
    GOODS_NAME_LIST: 'goodsNameList',
    PARENT_ID: 'parentId',
    PARENT_TITLE: 'parentTitle',
    START_DATE: 'startDate',
    END_DATE: 'endDate',
    UPDATED_AT: 'updatedAt',
    CREATED_AT: 'createdAt',
    STATUS: 'status',
    LOCKED: 'locked',
  },
  APPROVAL_REQUEST: {
    NO: 'no',
    APPROVAL_REQUEST_ID: 'approvalRequestId',
    TARGET_TYPE: 'targetType',
    TARGET_ID: 'targetId',
    ITSVC_NO: 'itsvcNo',
    REQUEST_KIND: 'requestKind',
    APPROVAL_STATUS: 'approvalStatus',
    PAYLOAD_BEFORE: 'payloadBefore',
    PAYLOAD_AFTER: 'payloadAfter',
    REQUESTER_NAME: 'requesterName',
    REQUESTER_DEPT_NAME: 'requesterDeptName',
    LAST_ACTOR_NAME: 'lastActorName',
    REQUESTED_AT: 'requestedAt',
    LAST_UPDATED_AT: 'lastUpdatedAt',
    IS_RETRACTED: 'isRetracted',
    IS_APPLIED: 'isApplied',
    APPLIED_AT: 'appliedAt',
  },
  LOGIN_HISTORY: {
    NO: 'no',
    LOGIN_HISTORY_ID: 'loginHistoryId',
    KC_USER_ID: 'kcUserId',
    USERNAME: 'username',
    EMP_NO: 'empNo',
    EMP_NAME: 'empName',
    LOGIN_AT: 'loginAt',
    LOGOUT_AT: 'logoutAt',
    LOGIN_IP: 'loginIp',
    LOGOUT_IP: 'logoutIp',
    USER_AGENT: 'userAgent',
    RESULT: 'result',
    FAIL_REASON: 'failReason',
  },
  USER_ROLE_CHANGE_HISTORY: {
    NO: 'no',
    HISTORY_ID: 'historyId',
    KC_USER_ID: 'kcUserId',
    USERNAME: 'username',
    EMP_NO: 'empNo',
    EMP_NAME: 'empName',
    ROLE_ID: 'roleId',
    ROLE_CODE: 'roleCode',
    ROLE_NAME: 'roleName',
    CHANGE_TYPE: 'changeType',
    ITSVC_NO: 'itsvcNo',
    REASON: 'reason',
    BEFORE_STATE: 'beforeState',
    AFTER_STATE: 'afterState',
    CHANGED_BY: 'changedBy',
    CHANGED_BY_USERNAME: 'changedByUsername',
    CHANGED_AT: 'changedAt',
  },
} as const;

export const {
  NO,
  APPROVAL_REQUEST_ID,
  TARGET_TYPE,
  TARGET_ID,
  ITSVC_NO,
  REQUEST_KIND,
  APPROVAL_STATUS,
  PAYLOAD_BEFORE,
  PAYLOAD_AFTER,
  REQUESTER_NAME,
  REQUESTER_DEPT_NAME,
  LAST_ACTOR_NAME,
  REQUESTED_AT,
  LAST_UPDATED_AT,
  IS_RETRACTED,
  IS_APPLIED,
  APPLIED_AT,
} = TABLE_LABELS.APPROVAL_REQUEST;
